### PR TITLE
DOCS Fix Scrutinizer badge in readme

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Comment by dhensby** [comment]
@robbieaverill who add https://scrutinizer-ci.com/g/silverstripe/comment-notifications/ ? because it exists at https://scrutinizer-ci.com/g/silverstripe-labs/comment-notifications/ and just needs renaming (but I can't do that now the new one exists because I don't have permissions to delete the new one)

**Comment by robbieaverill** [comment]
@dhensby I've deleted the SS repo, I don't have permission on Scrutinizer to change labs back to SS

**Comment by dhensby** [comment]
it's been done :)

**Comment by robbieaverill** [comment]
Thanks!

**Pull request merged**
