### PR TITLE
added check to see if owner->hasMethod('updateNotificationRecipients')

### PR DESCRIPTION
**Pull request by Makreig**
by checking for this, we can add the function to the object we are extending, instead of writing an additional extension to the object

### CODE REVIEW

**Review by dhensby — CHANGES_REQUESTED** [review]
This is going to break existing functionality where an extension expects to be able to manipulate the list regardless of implementation on the `owner`.

I think it'd be better to call `invokeWithExtensions` instead.

**Comment by Makreig** [comment]
wasn't aware of that call, that would be better...
however, its worth noting, that the current method isn't working for me when attempting to change the array on an extension.
I've created a custom object for my project and extended it after adding the notifiable extension, but the list isn't altered

**Comment by dhensby** [comment]
You need to make sure your extension method passes the list my reference:

``` php
class MyExtension extends DataExtension {

    public function updateNotificationRecipients(&$list, $comment) {
        $list[] = "whavever";
    }

}
```

**Comment by Makreig** [comment]
its the ampersand that catches people out...

**Comment by dhensby** [comment]
> its the ampersand that catches people out...

Yep - if it's not an object then it needs to be passed by reference and thus the `&` is needed.

**Comment by robbieaverill** [comment]
@Makreig  would you mind rebasing this PR?

**Comment by dhensby** [comment]
Is there a reason why we can't use `invokeWithExtensions`? this change still looks like it'll break situations where there are extensions expecting to be called regardless of if there's a method on the original object or not...

**Pull request closed without merging**
